import pytest
import numpy as np

raise Exception('test')